name: 🧱 Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: ♻️ Validate
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v6
      - name: 🔧 Setup Zig
        uses: mlugg/setup-zig@v2
      - name: 📦 Install dependencies
        run: |
          sudo apt update
          sudo apt install --yes libarchive-dev libalpm-dev
      - name: 🧪 Check project
        run: zig build test

